name: ppx_spice publish

on: [workflow_dispatch]

jobs:
  build_linux:
    name: ${{ matrix.os }}/node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
    container:
      image: alexfedoseev/alpine-node-yarn-esy:0.0.4
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Add tar
        run: apk add --no-cache tar

      - name: Install
        run: esy install

      - name: Print esy cache
        id: print_esy_cache
        run: node ../.github/workflows/print_esy_cache.js

      - name: Try to restore dependencies cache
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Build
        run: esy b

      - name: Build release-static
        run: esy release-static

      - name: Copy built PPX file
        run: |
          mv ./_build/default/bin/bin.exe ppx.exe

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: src/ppx.exe
          if-no-files-found: error

  build_macos:
    name: ${{ matrix.os }}/node-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    strategy:
      matrix:
        node-version: [12.x]
        os: [macOS-latest]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Install esy
        run: |
          npm install -g esy

      - name: Try to restore install cache
        uses: actions/cache@v1
        with:
          path: ~/.esy/source
          key: source-${{ hashFiles('**/index.json') }}

      - name: Install
        run: esy install

      - name: Print esy cache
        id: print_esy_cache
        run: node ../.github/workflows/print_esy_cache.js

      - name: Try to restore dependencies cache
        id: deps-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Build
        run: esy b

      - name: Copy built PPX file
        run: |
          mv ./_build/default/bin/bin.exe ppx.exe

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: src/ppx.exe
          if-no-files-found: error

  publish:
    needs: [build_linux, build_macos]
    name: (only on release) Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Download linux artifacts
        if: success()
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest
          path: binaries/linux

      - name: Download macOS artifacts
        if: success()
        uses: actions/download-artifact@master
        with:
          name: macOS-latest
          path: binaries/darwin

      - name: Move artifacts
        if: success()
        run: |
          mkdir -p bin
          mv binaries/linux/ppx.exe ppx-linux.exe
          mv binaries/darwin/ppx.exe ppx-osx.exe

      - name: Publish
        if: success()
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
